class XpathMap:

    map_tier1_new = {'gl_locator': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[3]/div/h3/span',
                     'gl_pol_number': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[2]/div/div/div/slot/records-record-layout-row[10]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'gl_eff_date': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[2]/div/div/div/slot/records-record-layout-row[1]/slot/records-record-layout-item[1]/div/span/slot/lightning-input/lightning-datepicker/div/div/input',
                     'gl_exp_date': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[2]/div/div/div/slot/records-record-layout-row[2]/slot/records-record-layout-item[1]/div/span/slot/lightning-input/lightning-datepicker/div/div/input',
                     'gl_each_occur': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[2]/div/div/div/slot/records-record-layout-row[5]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'gl_op_agg': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[2]/div/div/div/slot/records-record-layout-row[6]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'gl_insurer': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[2]/div/div/div/slot/records-record-layout-row[11]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'al_locator': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[4]/div/div/div/slot/records-record-layout-row[1]/slot/records-record-layout-item[1]/div/span/slot/lightning-input/lightning-datepicker/div/label',
                     'al_pol_number': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[3]/div/div/div/slot/records-record-layout-row[8]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'al_eff_date': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[3]/div/div/div/slot/records-record-layout-row[1]/slot/records-record-layout-item[1]/div/span/slot/lightning-input/lightning-datepicker/div/div/input',
                     'al_exp_date': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[3]/div/div/div/slot/records-record-layout-row[2]/slot/records-record-layout-item[1]/div/span/slot/lightning-input/lightning-datepicker/div/div/input',
                     'al_comb_limit': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[3]/div/div/div/slot/records-record-layout-row[4]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'al_insurer': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[3]/div/div/div/slot/records-record-layout-row[9]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'umb_locator': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[5]/div/div/div/slot/records-record-layout-row[1]/slot/records-record-layout-item[1]/div/span/slot/lightning-input/lightning-datepicker/div/label',
                     'umb_pol_number': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[4]/div/div/div/slot/records-record-layout-row[6]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'umb_eff_date': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[4]/div/div/div/slot/records-record-layout-row[1]/slot/records-record-layout-item[1]/div/span/slot/lightning-input/lightning-datepicker/div/div/input',
                     'umb_exp_date': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[4]/div/div/div/slot/records-record-layout-row[2]/slot/records-record-layout-item[1]/div/span/slot/lightning-input/lightning-datepicker/div/div/input',
                     'umb_each_occur': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[4]/div/div/div/slot/records-record-layout-row[3]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'umb_insurer': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[4]/div/div/div/slot/records-record-layout-row[7]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'wc_locator': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[5]/div/div/div/slot/records-record-layout-row[17]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-checkbox/lightning-input/label/span',
                     'wc_pol_number': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[5]/div/div/div/slot/records-record-layout-row[10]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'wc_eff_date': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[5]/div/div/div/slot/records-record-layout-row[1]/slot/records-record-layout-item[1]/div/span/slot/lightning-input/lightning-datepicker/div/div/input',
                     'wc_exp_date': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[5]/div/div/div/slot/records-record-layout-row[2]/slot/records-record-layout-item[1]/div/span/slot/lightning-input/lightning-datepicker/div/div/input',
                     'wc_each_acci': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[5]/div/div/div/slot/records-record-layout-row[6]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'wc_each_emp': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[5]/div/div/div/slot/records-record-layout-row[7]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'wc_pol_limit': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[5]/div/div/div/slot/records-record-layout-row[8]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input',
                     'wc_insurer': '/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_certificate_of_insurance__c___012f1000000n7xuaaq___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[5]/div/div/div/slot/records-record-layout-row[11]/slot/records-record-layout-item[1]/div/span/slot/records-record-layout-base-input/lightning-input/div/input'
                     }


